### Global Variables
@baseUrl = http://localhost:8080

### Health check
# @name healthCheck
# @request GET /health
# @response 200 OK
GET {{baseUrl}}/health HTTP/1.1

### Generates a new qr code
# @name generateQrCode
# @request POST /qrcode
# @response 201 Created
POST {{baseUrl}}/qrcode HTTP/1.1
Content-Type: application/json

{
  "text": "https://google.com"
}
